- name: "Declare install folder"
  set_fact:
    install_folder: "{{ spiderfoot | split('/') | last | split('.') | first }}"

- name: "Download Spiderfoot"
  git:
    repo: "{{ spiderfoot }}"
    dest: "/opt/py_apps/{{ install_folder }}"
    single_branch: true
    version: master

- name: "Install the requirements"
  pip:
    requirements: requirements.txt
    chdir: "/opt/py_apps/{{ install_folder }}"

- name: "Install the app"
  file:
    src: "/opt/py_apps/{{ install_folder }}/sf.py"
    dest: /usr/local/bin/sf
    state: link
    mode: 0755
